### ISSUE TITLE
Errore di formattazione nell'indice iniziale

### ISSUE THREAD

**Issue by m1gwings** [m1gwings/ing-sw-cheatsheet#30]
Nella prima facciata del PDF, l'ultimo elemento dell'indice è
Testing# Java
e manca il titolo del capitolo su Java.
Manca un a capo dopo l'indice

**Comment by francescogemma** [comment]
> Nella prima facciata del PDF, l'ultimo elemento dell'indice è Testing# Java e manca il titolo del capitolo su Java. Manca un a capo dopo l'indice

Ho fixato, mettendo un a capo, in #29

**Comment by m1gwings** [comment]
Sì ho visto, grande 👍🏼
